name: restaurant_app
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core:
  navigator:
  firebase_auth:
  fluttertoast:
  shared_preferences:
  firebase_storage:
  cloud_firestore:
  device_preview:
  animated_splash_screen:
  introduction_screen:
  flutter_svg:
  shimmer:
  sizer:
  smooth_page_indicator:
  consumer:
  dio:
  modal_progress_hud_nsn:
  flutter_spinkit:
  google_fonts:
  font_awesome_flutter:
  country_code_picker:
  location:
  otp_text_field:
  provider:
  bottom_navy_bar:
  easy_localization:
  hexcolor: ^2.0.6
  badges:
  geocode:
  flutter_map:
  latlong2:
  flutter_rating_bar:
  connectivity:
  flutter_bloc:
  bloc:
  one_context:
  google_sign_in:
  toggle_switch:
  pixel_perfect:
  fluttericon:
  expandable:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/images/
    - asset/Language/
    - asset/responsive/

  fonts:
    - family: Tajawal
      fonts:
        - asset: asset/fonts/Tajawal/Tajawal-Bold.ttf
        - asset: asset/fonts/Tajawal/Tajawal-Black.ttf
        - asset: asset/fonts/Tajawal/Tajawal-ExtraBold.ttf
        - asset: asset/fonts/Tajawal/Tajawal-ExtraLight.ttf
        - asset: asset/fonts/Tajawal/Tajawal-Medium.ttf
        - asset: asset/fonts/Tajawal/Tajawal-Regular.ttf
